version: '2'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 32080:80
